<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RuntimeIdentifiers>win-arm64</RuntimeIdentifiers>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Deep.Protocol" Version="[0.3.0-p04.b887fa0]" />
    <PackageReference Include="Deep.Protocol.ProfileCarrier" Version="[0.2.0-p14.69a712a]" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.9" />
    <PackageReference Include="Sodium.Core" Version="1.4.1" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher" Version="2.1.11" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Mnemonic\english.txt"
                      LogicalName="Deep.Client.Shared.Resources.Mnemonic.english.txt" />
  </ItemGroup>

</Project>
